[book]
authors = ["JordiMateoUdL"]
language = "ca"
multilingual = false
src = "src"
title = "HandsOns en Administració i Virtualització de Sistemes"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true

[output.html.code.hidelines]
sh = "~"